--- #YAML:1.0
name:               Acme-CPANAuthors-Search
version:            0.02
abstract:           A very simple module for searching CPAN module authors.
author:
    - Mohammad S Anwar <mohammad.anwar@yahoo.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Entities:  1.35
    HTTP::Request:   1.40
    LWP::UserAgent:  2.33
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
